# Dockerfile
FROM bitnami/mysql:latest

# Set the MySQL root password (replace with a secure password)
ENV MYSQL_ROOT_PASSWORD=NewDawn@2025
ENV MYSQL_DATABASE=mydatabase
ENV MYSQL_USER=myuser
ENV MYSQL_PASSWORD=mypassword

# Expose the MySQL port
EXPOSE 3306
