# docker-compose.yml
version: '3.8'

services:
  mysql:
    build: .
    container_name: bitnami_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/bitnami/mysql
    restart: always

volumes:
  mysql_data: # Named volume to persist MySQL data
